FOOTER_TEXT = ['Bible Teachings', 'Bible Questions Answered', 'Bible Verses Explained', 'Bible Study Course',
               'Bible Study Tools', 'Peace & Happiness', 'Marriage & Family', 'Teens & Young Adults', 'Children',
               'Faith in God', 'Science & the Bible', 'History & the Bible', 'Library', 'Bibles', 'Magazines',
               'Books & Brochures', 'Article Series', 'Meeting Workbooks', 'Guidelines', 'JW Broadcasting®', 'Videos',
               'Music', 'Audio Dramas', 'Dramatic Bible Readings', 'News', 'About Us', 'Frequently Asked Questions',
               'Request a Visit', 'Contact Us', 'Bethel Tours', 'Meetings', 'Memorial', 'Conventions', 'Activities',
               'Experiences', 'Around the World']
FOOTER_LINKS = ['https://www.jw.org/en/bible-teachings/', 'https://www.jw.org/en/bible-teachings/questions/',
                'https://www.jw.org/en/bible-teachings/bible-verses/',
                'https://www.jw.org/en/bible-teachings/guided-bible-study-course/',
                'https://www.jw.org/en/bible-teachings/bible-study-tools/',
                'https://www.jw.org/en/bible-teachings/peace-happiness/',
                'https://www.jw.org/en/bible-teachings/family/', 'https://www.jw.org/en/bible-teachings/teenagers/',
                'https://www.jw.org/en/bible-teachings/children/',
                'https://www.jw.org/en/bible-teachings/faith-in-god/', 'https://www.jw.org/en/bible-teachings/science/',
                'https://www.jw.org/en/bible-teachings/history/', 'https://www.jw.org/en/library/',
                'https://www.jw.org/en/library/bible/', 'https://www.jw.org/en/library/magazines/',
                'https://www.jw.org/en/library/books/', 'https://www.jw.org/en/library/series/',
                'https://www.jw.org/en/library/jw-meeting-workbook/', 'https://www.jw.org/en/library/guidelines/',
                'https://www.jw.org/en/library/videos/#en/categories/VODStudio',
                'https://www.jw.org/en/library/videos/', 'https://www.jw.org/en/library/music-songs/',
                'https://www.jw.org/en/library/audio-bible-dramas/',
                'https://www.jw.org/en/library/dramatic-bible-readings/', 'https://www.jw.org/en/news/',
                'https://www.jw.org/en/jehovahs-witnesses/', 'https://www.jw.org/en/jehovahs-witnesses/faq/',
                'https://www.jw.org/en/jehovahs-witnesses/request-a-visit/',
                'https://www.jw.org/en/jehovahs-witnesses/contact/',
                'https://www.jw.org/en/jehovahs-witnesses/bethel-tours/',
                'https://www.jw.org/en/jehovahs-witnesses/meetings/',
                'https://www.jw.org/en/jehovahs-witnesses/memorial/',
                'https://www.jw.org/en/jehovahs-witnesses/conventions/',
                'https://www.jw.org/en/jehovahs-witnesses/activities/',
                'https://www.jw.org/en/jehovahs-witnesses/experiences/',
                'https://www.jw.org/en/jehovahs-witnesses/worldwide/']
